//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsViewed
    {
        public int idProduct { get; set; }
        public int idUser { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
