# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d5KTKhWFDIzLScJGKNq54AsEjnhg6w4w
"""

!pip install -q mahotas
!pip install -q milk
!pip install -q jug 
# !pip install PyDrive
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2

from PIL import Image

from glob import glob
import mahotas
import mahotas.features
import milk
from jug import TaskGenerator
import csv
import os
from skimage import io

def features_for(imname):
#     img1 = mahotas.colors.rgb2grey(imname)
    img1 = mahotas.imread(imname)
    img = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
  
#     img = mahotas.colors.rgb2grey(img1)
#     img = rgb2gray(img1)
    return mahotas.features.haralick(img).mean(0)

# def rgb2gray(rgb):
#     return np.dot(rgb[...,:3], [0.299, 0.587, 0.114])
  
def Write_File(list_dict):
#   with open('haralick_noHuman.csv', 'wb') as csvfile:
#     harawriter = csv.writer(csvfile, delimiter=' ', quotechar='|', quoting=csv.QUOTE_MINIMAL)
#     harawriter.writerow(list_dict)
  myFile = open('haralick_no_human.csv', 'w', newline='')  
  with myFile:
    myFields = ['fileName','a','b','c','d','e','f','g','h','i','j','k','l','m']
    writer = csv.DictWriter(myFile, fieldnames=myFields)
    writer.writeheader()
    for data in list_dict:
      writer.writerow(data)


searchPath = '/content/'
# from google.colab import files
# uploaded = files.upload()

listValues = []
i = 0
# for i in range(96):
#   a = 'img ('+ str(i+1) + ').jpg'
for file in os.listdir(searchPath):
    i = i + 1
    print(i)
    if file[0] == 'l':
#     im = Image.open(file)
      a = str(file)
      b = features_for(file)
      diction = {'fileName' : a, 'a': b[0],'b':b[1],'c':b[2],'d':b[3],'e':b[4],'f':b[5],'g':b[6],'h':b[7],'i':b[8],'j':b[9],'k':b[10],'l':b[11],'m':b[12]}
      print(diction)
      listValues.append(diction)

Write_File(listValues)

from google.colab import drive
drive.mount('/content/drive/My Drive/No_Human')