# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d5KTKhWFDIzLScJGKNq54AsEjnhg6w4w
"""

# !pip install -q mahotas
# !pip install -q milk
# !pip install -q jug 
# # !pip install PyDrive


from PIL import Image

import glob
import mahotas
# import mahotas.features
# import milk
# from jug import TaskGenerator
import csv
import os
##import cv2


def features_for(imname):
    img = mahotas.imread(imname)
    return mahotas.features.haralick(img).mean(0)

##def features_forgrey(imname):
###     img1 = mahotas.colors.rgb2grey(imname)
##    img1 = mahotas.imread(imname)
####    img = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
##  
##    img = mahotas.colors.rgb2grey(img1)
##    img = rgb2gray(img1)
##    return mahotas.features.haralick(img).mean(0)


def Write_File(list_dict,type):
#   with open('haralick_noHuman.csv', 'wb') as csvfile:
#     harawriter = csv.writer(csvfile, delimiter=' ', quotechar='|', quoting=csv.QUOTE_MINIMAL)
#     harawriter.writerow(list_dict)
  myFile = open('haralick_no_human25_4 '+ type +'.csv', 'w', newline='')  
  with myFile:
    myFields = ['fileName','a','b','c','d','e','f','g','h','i','j','k','l','m']
    writer = csv.DictWriter(myFile, fieldnames=myFields)
    writer.writeheader()
    for data in list_dict:
      writer.writerow(data)


searchPath = 'C:\\Users\\al00993\\Documents\\GitHub\\FYP\\sprint4\\data\\images\\sachwani_cropped_images\\Yelo cropped\\**\\*.jpg'
# from google.colab import files
# uploaded = files.upload()

listValues = []
listValuescolor=[]
listValuesgrey=[]
i = 0
# for i in range(96):
#   a = 'img ('+ str(i+1) + ').jpg'
for filename in glob.glob(searchPath, recursive=True):
    # print(filename)
    i = i + 1
##    print(i)
    # im = Image.open(filename)
    a = str(filename.split('\\')[-1])
##    print(a)
    b = features_for(filename)
##    c = features_forgrey(filename)
##    print(b)
    dictioncolor = {'fileName' : a, 'a': b[0],'b':b[1],'c':b[2],'d':b[3],'e':b[4],'f':b[5],'g':b[6],'h':b[7],'i':b[8],'j':b[9],'k':b[10],'l':b[11],'m':b[12]}
    listValuescolor.append(dictioncolor)
##    dictiongrey = {'fileName' : a, 'a': c[0],'b':c[1],'c':c[2],'d':c[3],'e':c[4],'f':c[5],'g':c[6],'h':c[7],'i':c[8],'j':c[9],'k':c[10],'l':c[11],'m':c[12]}
##    listValuesgrey.append(dictiongrey)

Write_File(listValuescolor,'color')
##Write_File(listValuesgrey,'greyscale')
